matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1
      script:
        - dotnet restore
        - dotnet build
        - dotnet test ManageCoursesUi.Tests
      deploy:
        - provider: script
          script: bash deploy.sh dev
          on: master
        - provider: script
          script: bash deploy.sh staging
          on: staging
        - provider: script
          script: bash deploy.sh prod
          on: production
    - language: node_js
      node_js:
        - 10.8
      cache:
        directories:
          - "~/.npm"
          - "~/.cache"
        override:
          - npm ci
      before_script:
        - cd src/ui
        - npm ci
      script:
        - npm test
        - cd ../..
env:
  global:
    # AZURE_WA_PASSWORD
    - secure: Jevjau9bkjgarHgHLBmptIRIysFdMWYaYjMQdJNd61GS1hDIZqwdIr843hfnvEbgRIJRa/8oCpW/2iasjC9qQ6ZZuM8Km8Ay75qWEpaWRWCddq5fSKtIb6pnzRhC0NsviMVRluJvlQYA5b4NnOosS26913ylk1PKgfEcV5s/nxb7UxiEvoSeCjLxhOq1SXhM8SS2D8kjXZz7xYEigTGzNc4e6ZMj44b4O1sDZAQPxpKc6ELAi8ncZXZax5ZuuUsUMKT+qwo1JbDcJE2CwUXgWR/8yUFWNVDkjM0N0+z2m3wEJhOcYJV0q7X2YavI920KAp4iAbOLqRXd/uaaxW5AorzJFP4FyH2fBtYsISGZUeLXp20qgeJoz3XxZJP4LjCttXGNU2CTNpupuqCudJaT0D4HIGU4GyOnki24sRbnbeFjRstx1/+VLoKNndgZW49T4KuzURXudKsNfjM4n0SYJwbiWUSzOqJJ3CWdXarFo82HARuYXa8gi7QiigV0U6VvLQbXp6RZLtDHE4xYW7TXmrilx7o77kePR1duqGehgys+ICJy8JW7YawSYCo9W4RolL6l5gDTMCSp1vk9vfXBWevngbWi5Px/O4Qhb3A+JfPiW/eTflNqTlcZRCi4YvYWpl3Dbfkl09HvBqAmpAGAKdFHOak63E6iiIB2E5Xlfew=
    # APP_CREDENTIALS_DEV_PWD
    - secure: 0oP625x094Gd9nDqfvGSAkX6Ej8asPsIKdvLc0Bqe/ISMKTTLFhR73lQ3QBGrvaDgVYPKLVEijk9WQR2iTr9CovWyYYkwoTg1pzw45Pjn09rmt65A+h1NM77rSIUSSkdJ5W9Mct/VlxfEd0FN6Uj/lQOthDKMGs3uG8iSj/DkH8whxN9hOleqAF4hIC6NeVbP+cCg/CSHFZhuZ36SAeBTbo9vb9vbBrK59/gSfow8PYVZ39DNEgIqNpYfJx3NS71AN9cweBJwQVla8gmQav8dOCfXrXsIiKqEY6wujW2RTr20RT457PF1a4F1LU+BxOA++ApLEK7GDgzgioo6f0wCWI9gJrakjUP/RpJMfWSBmW7eEkiLzE94R2/Ujmq7eXaRXMR5kgbXm3juCr9aVfNCu0F47FsY69NEAbvJtnnhzLUkCNbqWJDMs2uWMWxiAmZqV4plEoGlCDRUhCl3Fel8xGOs8SMmRmXaa43UXG/0BOw92KmMDPN0PrsBfZzFdzLDIsVwX7Kronts20SvSiay5NNVAIcqGfJMSdyDBQA1KcW+avkw/2SIlPQjBLmaXJBs4tb1sKwEr93aToQdWvINc04r24pJjBbx0nypqocoRPgxSg7kDfBoA91RLWADrd2V9/7plwoB2OBU2hoQPSIOIGqDb11lMeamG0GJjUFfNw=
    # APP_CREDENTIALS_STAGING_PWD
    - secure: oMtTQlx/sUGWbVR1RizvWWnzemp1KXyqb2Dck2Cl5BifQGrDDg8MA6pGn6hiHKA3oAf8HhKxP/OeSgBnVcKePOzICtMqaYNA2tQ9lRHEfyY2cSC8a93/jVtxg1KC5Qgs1Qd207uhyz6wAZD4ocnuwCCii7ahCM4Jg4a8c+mijytnjHwVkhRm+69lFGUrmyfzEH2qxz0hdl07zkzYC+MH3VR5Po1gJthQYyEICR5m/2V+4v5m9BVokLf0md2NgCWecq6coiHHoVlrQCqA2dH0QfX2Gt9MVrADmkGHfBo8cXGVMEmbSAHKGjUer5AJZD8mH28ThmgCDSQqtD0s7a1x5+bLI7NQNoCQtpFjcbWxOslZMY/9kmyU7Hg+K0YhSPezdu5oMf8A8A0CVe/z+P8RTNFY41qb9fwz7vAGdyoZcQsoRkDbds254RRApwsf5w0iVM0ZtHUHoxGniZwB6vAK77LsX2Rl74YaI51lSZjWK+wHDT9rYpywqKMB1rJ+7mXeG3Ju6hIVjTPgVIaVJuUDYEnhrklqlNDDfxv5JZZaaZefUYmKkCcN11wsm7lPGbrhxKQPvAGHwLek+jd0Ftov6ezbAoRyDKpczNhv+ISOgVxsMwn5YOXhTH9iY4VaZhju5tVGYrMogvdFgbsin1rwDtXT4ArcAm9EKlRlfmlzsO0=
    # APP_CREDENTIALS_PROD_PWD
    - secure: JX/8Unw6xPJwop5CmmvU7ftHIDyTgTzz4ZrgeK0XPEU05VkR56sLyk09seQosoEdsw7esvkEnrLXzvDwJfu/ZeorNt5QawSI3QEoiwoL4Xle6XAI+qg3G/0U1M5ayEuWl0RoXIrePnXoNqXEcC1KMDIKPFmCbb7UsB5j2OjB29eIn/y9JwUI/Q36bqEM6pHuRG5iTyM5QpsOvCf13/LrEAVYhbEp9OqbtUBsMw/RRioXVeLVXZhMh9N0TY76CqAaan1J93rOURxMP1SN8oSdVRr1G12ZhXMrKeoxy64JvD6ZsARSIQMVHaCLHOvBJ8LdnbVRbUvvxff7VJsvAEdjvk1ayFlnF0WeDMTPJUy60BJxbh2Bc4PSnNHAHkVrq5O12DU+k778FnDWqgkzxmwC53Q10/LMhDTjCZblfOHHKKYiXPSC6tubC3eUkuBwCMtuJI2Q1emqPKOtAn+lpv97MC6iky/b+Xx0PwkPfO75+ZNPGt5PnDHvQ0fQ5olaSZ+iHh4HDLBXCndYyiXN0ua4XEqGQJLB4Yi/8eGumgM2Mr8ZzVsn9t8fxwitAQW8RqXJ2jYdEahClGGvTq2P8BLa/ylMh2LldiX9yVXcuj/AnVEqA8DxOvsX7S9pNYB+VEoxH3oHqQFIUHbnn/VCFALbn+8uQBniRFRcoAgarOgywVw=
notifications:
  slack:
    secure: T/CYoV0gsD7upCYiGq4Ev/jbbHWo4AVEw8m0+qaGFgzrnbStbtV50gwygD/ZJM6KOaXL4U3WZMeWl41EDB2PXaETWxu7KhGIYfDDnm1S3XvsOCsh/HHKNifbM6uEmGGC5947598eZzr+kZeZD4zunD31wYylOAR7ScKpM/iucN3MU9N55GD0wr2xiALacQ8l1WwCNLQSQdPXpkgZ1IIlT+jio1YQqkn4mu010PpwzwFfZw3nQpM6bpGxGtJQpizVmmIYDoDDRlI+qkKOBZyIY0BO8bmqzPQRhx1x+y9DDsh+NaISDk1sjX5pmRifDtQqo55eHVNhQZbXNq5lVlq0hn3cdbARdlINEIXx2wpP3qBAaZX7/kJm+y/xjqIvsegclZ1YWUKalOivrWh4DNS+hR4SfvYtKYBtQ+jsB+Na9p8UbG9mx97B+lAT4K6Fwuoxbh+nN+bI/XVEJY6H2CTZVjmxPv/66us3vJ4282GUqPK5kc2LPTGXqwJXQRmh3okFytxdnkfzLSL4gLPKuLBKSfyxRQNnqeELSO+04P9Q0cVpFjlP3M6bTOsGVPPeMvgYmbVoj+2DVofIlvjM0c0w5QTXMBfQrejSnhEHMHnFgF1ocap86qUd4ZdwN27VtgDM+3mtwuafWBaWPYeQOsiHXmF5OAbU786DJnzeMzUo444=
  on_success: always
  on_failure: always
